redis:
  - virtualCount: 31
    option:
      host: '127.0.0.1'
      port: 6379
      maxConnLifetime: 600
      maxIdle: 10
      maxActive: 20
      connectTimeout: 300
      readTimeout: 300
      writeTimeout: 300